### ISSUE TITLE
Add .filter.table.startingChannel to to the Filter Playlist table

### ISSUE THREAD

**Issue by joshjryan** [SCP002/xTeVe#26]
It would be very nice if you could view the Starting Channel for each filter group from the table (instead of having to click on the row, to view it in the popup).

**Comment by SCP002** [comment]
Will do but unsure if will have enough free time today 🤔, so perhaps will make a new release with all the other fixes tomorrow. Thanks for your patience)
By the way, what do you think about this? https://github.com/SCP002/xTeVe/commit/60a755af5752b8cf59fb3441122751e8e035117d unsure if it's fine to remove unfiltered channel limit or not. With this change, xTeVe will only display a warning about exceeding 480 channels but not disable all streams entirely.
