### ISSUE TITLE
SSL + Add protocol to url if missing

### ISSUE THREAD

**Issue by JReming85** [SCP002/xTeVe#29]
**Is your feature request related to a problem? Please describe.**
I havent tried your fork yet but with the original version I ran into an issue where Plex is rewriting the http protocol to https causing channel icons/posters to not show up.

As for the add HTTPS:// if missing, ran into an issue where some of my posters did not load because they were missing the protocol and plex interpreted it as a internal file causing a 404 when loading the img.

**Describe the solution you'd like**
Simple solution add SSL support

**Describe alternatives you've considered**
I currently am using a combo of a nginx reverse proxy for the SSL, and a few sed replace scripts to rewrite the xml file with the proper changes

**Additional context**
I do have my plex setup a little different then most, I have relay turned off and ssl enabled with a custom cert.  It is possible that combo is whats forcing me to only use ssl urls if no one else is having this issue.

**Comment by SCP002** [comment]
Noticed the original issue https://github.com/xteve-project/xTeVe/issues/308 👀
Will try to figure it out

**Comment by SCP002** [comment]
Can I ask you if this is still reproducible with the following Plex settings?
![Новый проект](https://user-images.githubusercontent.com/22541678/163681559-3daa5597-6291-4953-89ba-608e6027e9a0.jpg) (set fallback to "Always" / "On same network as server")

**Comment by JReming85** [comment]
Looks like I lied about the SSL. I had it set to Secured Connections Preferred, just changed it to required and will test it later tonight or tomorrow night depending on when I make it home

**Comment by SCP002** [comment]
Btw here is how some errors related to URL's of posters or icons are ignored in code:
This:
https://github.com/SCP002/xTeVe/blob/f129cf55f8ebd85aa93b9563e03b915698ba762f/src/xepg.go#L933
Calls:
https://github.com/SCP002/xTeVe/blob/f129cf55f8ebd85aa93b9563e03b915698ba762f/src/internal/imgcache/cache.go#L47
And in this function, if parsing go wrong
https://github.com/SCP002/xTeVe/blob/f129cf55f8ebd85aa93b9563e03b915698ba762f/src/internal/imgcache/cache.go#L58-L61
It will not report about it, only return input URL as it was.

Not saying this will solve the issue, just sharing with you & myself what would be great to change in a future release.

**Comment by JReming85** [comment]
Sorry for the delay, just checked it and plex is still trying to load https for some reason

I recreated the nginx conf with ssl disabled, took the screenshot with it on but got the same result both times, plex is rewriting the http to https

Note this with image caching enabled

![image](https://user-images.githubusercontent.com/21246660/164044269-161c7b09-2352-43b6-8c9c-0422ac25e132.png)

Also I am using your build in this test, replaced the xteve app in the docker I am using

**Comment by SCP002** [comment]
Adding basic TLS support is work in progress right now. This project is a foreign codebase for me + I'm not a professional developer so it might take some time. Trying my best 👨‍💻

**Comment by JReming85** [comment]
Thanks a lot for attempting it, I really appreciate the effort.

**Comment by SCP002** [comment]
> Thanks a lot for attempting it, I really appreciate the effort.

Hey 👋 
Here is a new release https://github.com/SCP002/xTeVe/releases/tag/2.3.0.0000
You can either check out latest release notes from there or look at https://github.com/SCP002/xTeVe#tls-mode to see how this feature is implemented currently.

After enabling TLS mode, xTeVe should update it's database and then redirect you to HTTPS web interface automatically (give it a few seconds or type in https:// prefix manually).

❗ Do not forget to enable image caching back again, so Plex will refer to posters served by xTeVe (with https).

To be honest I by no means understand all this certification stuff under the hood and haven't managed to make google chrome trust own certificates on windows, still have to learn this topic and modify README.md accordingly, but for now, wrote it the way which seems logical 😅 

Side note from golang http server documentation, may be useful:

> If the certificate is signed by a certificate authority, the certFile should be the concatenation of the server's certificate, any intermediates, and the CA's certificate.

Please let me know if you will not figure out how to make it work or if this will not solve the problem.

**Comment by JReming85** [comment]
Will do, thank you so much for this update!

**Comment by JReming85** [comment]
Got another issue that stemmed from this.

Its defaulting to my devices 3rd IP (docker network), is there a way to specify the host ip?

**Comment by SCP002** [comment]
Oh, this must be https://github.com/xteve-project/xTeVe/issues/300, found in the original repository;
If so, I'll better create a new issue as it's not really relevant to TLS.

P.S: About TLS: https://github.com/SCP002/xTeVe/releases/tag/2.3.1.0000 -- starting from this version you don't have to download any certificates or anything from here just to let it start.

Moreover, it's not just about tvg-logo, as referenced in the issue above, and not really random, it sets the entire domain IP to the latest available in the list unless it's a loopback or link-local address:

Here:
https://github.com/SCP002/xTeVe/blob/b80a93c7be987a8198cd8ecf2ca8a168158a995b/src/toolchain.go#L320

Function overwrites the previous found IP with the last one matching until it sets IP to the last one in the list:
https://github.com/SCP002/xTeVe/blob/b80a93c7be987a8198cd8ecf2ca8a168158a995b/src/toolchain.go#L342

What do you think, should we have a way to select which one to use or select first as default?

**Comment by SCP002** [comment]
Moved to https://github.com/SCP002/xTeVe/issues/31
