### ISSUE TITLE
Store buffer in memory (instead of writing to disk)

### ISSUE THREAD

**Issue by joshjryan** [SCP002/xTeVe#30]
**Is your feature request related to a problem? Please describe.**
My clients buffer more often than I'd expect, when using the xTeVe (and ffmpeg and VLC) buffer.  I'm not exactly sure what's causing it, but looking at how much is written and read from disk is interesting.

**Describe the solution you'd like**
Might it be better to store the buffer in memory, instead of all the writes/reads to the temp directory?

**Describe alternatives you've considered**
N/A

**Additional context**
I just want to get some input on this thought. Feel free to let me know what you think.

**Comment by SCP002** [comment]
It would be better to determine the root cause, but until we figure it out ... yet another checkbox will never hurt 😉

**Comment by joshjryan** [comment]
@SCP002, dude! do you not have a day job? I hadn't even had time to look at how this should be implemented, and you already did it.
I'll pull down your changes and build it to give it a go.

**Comment by SCP002** [comment]
@joshjryan Kind of 😅 Will make a new release in, <= 2 hours from now, just need a small break 🙂

**Comment by joshjryan** [comment]
I just pulled your changes down and built it...I'll keep an eye on memory usage to see if anything is leaking.

**Comment by SCP002** [comment]
@joshjryan [Here ](https://github.com/SCP002/xTeVe/releases/tag/2.4.0.0000)is the "official" 🙃 build ready already.
P.S: Hope you don't have any unusual operation systems to try to run it at, because this time it built only for, basically, linux x64 and windows x64. Will try to fix it too.
