### ISSUE TITLE
Domain IP is always resolving to the latest available in the list of all net.InterfaceAddrs() returns

### ISSUE THREAD

**Issue by SCP002** [SCP002/xTeVe#31]
Unless it's a loopback or link-local address.

See:

https://github.com/SCP002/xTeVe/blob/b80a93c7be987a8198cd8ecf2ca8a168158a995b/src/toolchain.go#L320

https://github.com/SCP002/xTeVe/blob/b80a93c7be987a8198cd8ecf2ca8a168158a995b/src/toolchain.go#L342

**Comment by JReming85** [comment]
Personally I think it would be best to let the user select, with a fallback to 0.0.0.0.

That way they can either pick a interface or open to all interfaces.

p.s. thanks for the update

**Comment by SCP002** [comment]
Thought to also fit this https://github.com/SCP002/xTeVe/issues/30 in a new release, so will do it as soon as close that issue (hope in a day or two), but if you in a hurry, you can compile the project from the source by yourself, https://github.com/SCP002/xTeVe#build-from-source-code-go--golang

**Comment by SCP002** [comment]
@JReming85 [Here](https://github.com/SCP002/xTeVe/releases/tag/2.4.0.0000) is the new build, includes IP change and in-memory buffer settings options.

Hope you don't have any unusual operation systems to try to run it at, because this time it built only 3 binaries, thankfully for linux x64 and windows x64 inclusive.
Will try to fix it.

If you run any x32 bits operation system, freebsd, darwin (mac) or anything like that, let me know, ill send you a binary, compiled from code at this point in time https://github.com/SCP002/xTeVe/tree/04be477219d3ca3bc24903ebc5250d3551086d77
