### ISSUE TITLE
Docker image for this Xteve version

### ISSUE THREAD

**Issue by deku-m** [SCP002/xTeVe#36]
**Is your feature request related to a problem? Please describe.**
No this is not really a problem but more a request for support for downloadable docker image.

**Describe the solution you'd like**
I wonder if there are docker images available. 

**Describe alternatives you've considered**
You are the only one who is updating this application now with lots of fixes.

**Comment by SCP002** [comment]
Hello 👋 
TL;DR: Plan to fix a bug or two, create a new release and will try to make it and update the readme file accordingly.

I am not really familiar with docker (yet).

Wonder if it is possible to create a new, linux-comaptible docker image on my windows machine, or should I install some linux distro on top of a virtual machine...
In any case, sorry for the delay, will learn the topic and try to do this.

@SCP002 Link for myself: [howto](https://docs.docker.com/get-started/02_our_app/)

**Comment by deku-m** [comment]
> Hello 👋 TL;DR: Plan to fix a bug or two, create a new release and will try to make it and update the readme file accordingly.
> 
> I am not really familiar with docker (yet).
> 
> Wonder if it is possible to create a new, linux-comaptible docker image on my windows machine, or should I install some linux distro on top of a virtual machine... In any case, sorry for the delay, will learn the topic and try to do this.
> 
> @SCP002 Link for myself: [howto](https://docs.docker.com/get-started/02_our_app/)

No its already awesome you are improving the app and if the docker comes as well it would be great.
So i dont mind the delay. Im also not familiar with it sorry.

I only see alot of people using github as automation for docker i think with github actions.
https://event-driven.io/en/how_to_buid_and_push_docker_image_with_github_actions/
Then it will build new releases everytime you update the app.

**Comment by SCP002** [comment]
@deku-m Once again, sorry for the delay. Check it out https://github.com/SCP002/xTeVe#docker
