### ISSUE TITLE
Inactive channels are not filtered from the m3u8/dvr outputs

### ISSUE THREAD

**Issue by beardypig** [SCP002/xTeVe#43]
When channels are disabled in the "Mapping" section, they should not appear in either of the m3u8 or dvr outputs. However, this is currently not the case and all channels regardless of their state are returned.

version: 2.4.1.0000 

Thanks for your hard work on this fork @SCP002 :)

**Comment by SCP002** [comment]
Hmm. Having hard time trying to reproduce it in current (live) version.
I'll make a release after close one more issue, https://github.com/SCP002/xTeVe/issues/35.
And notify you when it's done (hope ~2 hours from now).

Can you please retry with version 2.5.0 when its out?

Tip 1: Make sure you've pressed the "Save" button in mapping menu after disabling a channel in mapping popup.
(click Done in popup, then click Save).

Tip 2: It takes a little bit of time for xTeVe to rebuild the database after changes were made, so there is a possibility when you recieve old playlist before it rebuilt. Easiest way to check if xTeVe is still busy is to press F5 (reload the page, see if it will respond with maintenance message) or check logs.

Tip 3: Make sure recieving side is not displaying a cached playlist. To exclude this possibility, easiest check is to open M3U link in browser (for example http://192.168.88.218:34400/m3u/xteve.m3u) when it's ready, press Ctrl + F and type in the name of any channel you've disabled. If it's not there - then we most probably have a caching issue on the reciever side.

**Comment by SCP002** [comment]
@beardypig https://github.com/SCP002/xTeVe/releases/tag/2.5.0.0000

**Comment by SCP002** [comment]
@beardypig think this issue might got fixed when [this line](https://github.com/SCP002/xTeVe/commit/125efd8b423a6e52f560c09abbbc3983e21804d7#diff-0f90f28f754d54b43d69b9e6272a4809ca09d9c5ee3f772ed6917fb68842fb37L557) was removed and replaced with chunk of code at lines 607 - 610 later in that file.

**Comment by SCP002** [comment]
@beardypig Can't reproduce in version 2.5.0, assuming it can be closed. Also, saw your docker repo. I've created my own image https://github.com/SCP002/xTeVe#docker
